apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
  labels:
    name: auth
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: grpc
  selector:
    name: auth
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: auth
  labels:
    name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
        - name: kite
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: auth-postgres
                  key: POSTGRES_URL
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid
                  key: apikey
            - name: KITE_WEB_URL
              value: "https://deploy.wtf"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /pubsub/creds.json
            - name: GOOGLE_PUBSUB_PROJECT_ID
              value: kite-prod-297314
            - name: JAEGER_SERVICE_NAME
              value: auth
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: PRIVATE_KEY_FILEPATH
              value: "/jwt/tls.key"
          volumeMounts:
            - name: pubsub
              mountPath: "/pubsub"
              readOnly: true
            - name: jwt
              mountPath: "/jwt"
              readOnly: true
          image: eu.gcr.io/kite-prod-297314/auth:8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: grpc
      volumes:
        - name: pubsub
          secret:
            secretName: pubsub-service-account
        - name: jwt
          secret:
            secretName: kite-jwt
