apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: "nginx"
  name: trace
  namespace: default
  labels:
    name: trace
spec:
  tls:
  - hosts:
    - trace.deploy.wtf
    secretName: deploy-trace-tls
  rules:
    - host: "trace.deploy.wtf"
      http:
        paths:
          - path: /
            backend:
              serviceName: jaeger-query
              servicePort: query
