apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: default
  labels:
    name: users
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: grpc
  selector:
    name: users
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: users
  labels:
    name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      name: users
  template:
    metadata:
      labels:
        name: users
    spec:
      containers:
        - name: kite
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: users-postgres
                  key: POSTGRES_URL
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /pubsub/creds.json
            - name: GOOGLE_PUBSUB_PROJECT_ID
              value: kite-prod-297314
            - name: JAEGER_SERVICE_NAME
              value: users
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
          volumeMounts:
            - name: pubsub
              mountPath: "/pubsub"
              readOnly: true
          image: eu.gcr.io/kite-prod-297314/users:21
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: grpc
      volumes:
        - name: pubsub
          secret:
            secretName: pubsub-service-account
