// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	Author  *User  `json:"Author"`
	Message string `json:"Message"`
}

type Post struct {
	Author   *User      `json:"Author"`
	Comments []*Comment `json:"Comments"`
}

type Signup struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
